### PR TITLE
Remove unused code from transliterate.ts

### PR DESCRIPTION
**Pull request by bt2901**
Remove the logic that handles anything unrelated to `type == 1` (cyr -> lat) and `type == 5` (lat -> cyr). Maybe 6 and 7 could be relevant too eventually, so leave them for now.

Remove the logic that handles `{}` (to leave parts of input unchanged), `<>` (to preserve html tags), and other special symbols (`teken` array)

Aside from the readability benefit, It should marginally improve performance.

### CODE REVIEW

**Comment by noomorph** [comment]
Is that basically a dead code you are removing?

**Comment by bt2901** [comment]
Yes, a lot of dead code. Jan used this function for other languages and conlangs. I'm assuming the dictionary will be used to translate single words (or short phrases), not multiparagraph HTML pages or something.

**Comment by noomorph** [comment]
@bt2901, could you investigate please what test coverage we have for this function?

**Comment by bt2901** [comment]
I could be mistaken (since I'm not very familiar with the system you are using), but as far as I can tell:

* only the `type == 1` (cyr -> lat) is tested; as far as I can see from the code, the actual website uses types `1`, `5` and `7` (see `getLatin`, `getCyrillic`, `getGlagolitic`).
* there are no Cyrillic nor Glagolitic letters in the `testCases.json` file, which I don't think is right.
* not all types of flavorization are tested
* the case of several words (i.e. there's a space in the input) is not tested. The Interslavic examples would be "да бы",  "повинно се", "настрашити се" (the last one even has conjugations). Maybe "кторы-небуд/кторы-либо/кто-небуд/что-небуд/что-либо" as well. Valid queries In other languages would be e.g. "for what reason" and "козлиная бородка"

**Comment by noomorph** [comment]
@bt2901 sounds good. I highly appreciate your time taken to analyze this.

What do you think if we process this change step by step? Maybe let's add the test cases for the transliteration and all the functionality currently in use before we merge the PR that drops the unused code, as a separate preceding PR?

**Comment by bt2901** [comment]
I think this is a good idea, but I don't understand how your testing system works. I think it only checks for declensions/conjugations, not for search query results? 

So, if we need different test cases - how do I go about adding them? I'm familiar with CI, but only for Python (using `pytest` and `pytest-cov` mainly)

**Comment by sonic16x** [comment]
@bt2901 please return logic related `Remove the logic that handles {} (to leave parts of input unchanged), <> (to preserve html tags), and other special symbols (teken array)` we are using now {} and it possible that we will use <> ans another special symbolsо

**Comment by noomorph** [comment]
Won't fix because of https://github.com/sonic16x/interslavic/pull/247 (the transliteration code is published separately from the dictionary).

**Pull request closed without merging**
